Homework6/tasktracker/lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug  :get_current_user
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  def get_current_user(conn, params) do
    user_id = get_session(conn, :user_id)
    if user_id do
      user = Tasktracker.Accounts.get_user!(user_id)
      assign(conn, :current_user, user)
    else
      assign(conn, :current_user, nil)
    end
  end


  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/task", PageController, :task

    resources "/users", UserController
    resources "/tasks", TaskController

    post "/session", SessionController, :create
    delete "/session",SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

Homework6/tasktracker/lib/tasktracker_web/templates/page/index.html.eex
<div class="row">
  <div class="col">
    <h1>Welcome to Task Tracker</h1>
    <%= form_tag("/session", method: :create) do %>
    <div class="form-group">
      Email
      <input type="email" name="email" placeholder="user@example.com">
    </div>

    <div class="form-group">
      <button class="btn btn-primary"> Log In</button>
      <%= link "Register", to: user_path(@conn, :new) %>
    </div>
    <% end %>
  </div>
</div>

Homework6/tasktracker/lib/tasktracker_web/templates/page/task.html.eex
<%= if @current_user do %>
<div class="col">
  <div class="row">
      <%= render TasktrackerWeb.TaskView, "form.html", Map.put(assigns, :action, task_path(@conn, :create)) %>
  </div>
</div>

<% end %>
<script>
  function complete(x){
    var final = "/tasks/"+x+"/edit"
    window.location.replace(final)
  }


</script>

<h1> Your Tasks </h1>

<div class="row">
  <div class="col-2">
    <h4> Title</h4>
  </div>
  <div class="col-2">
    <h4> Description</h4>
  </div>
  <div class="col-2">
    <h4> Status</h4>
  </div>
  <div class="col-2">
    <h4> Time</h4>
  </div>
</div>


<%= Enum.map Enum.filter(@tasks, fn(task) -> task.user_id == @current_user.id end), fn task -> %>
<div class="row">
  <div class="col-2">
    <strong><%= task.title %></strong>
  </div>
  <div class="col-2">
    <p><%= task.description %></p>
  </div>
  <%=if task.status==true do %>
  <div class="col-2">
    <p>Complete</p>
  </div>
  <% end %>
  <%=if task.status==false do %>
  <div class="col-2">
    <p>Incomplete</p>
  </div>
  <% end %>
  <%=if task.time==0 do %>
  <div class="col-2">
    <p>N/A</p>
  </div>
  <% end %>
  <%=if task.time>0 do %>
  <div class="col-2">
    <p><%= task.time %></p>
  </div>
  <% end %>
  <div class="col-2">
    <button onclick="complete(<%= task.id %>)"> Change Status</button>
  </div>
</div>

<% end %>